### ISSUE TITLE
BUG wheellog_csv/csv_to_gpx converter

### ISSUE THREAD

**Issue by b1oki** [alexandersobyanin/app.alexandersobyanin.ru#64]
```
2022-09-12T11:56:21.643107+00:00 heroku[router]: at=info method=POST path="/wheellog_csv/csv_to_gpx" host=app.alexandersobyanin.ru connect=0ms service=1935ms status=500 bytes=244 protocol=https
2022-09-12T11:56:21.642717+00:00 app[web.1]: [2022-09-12 11:56:21 +0000] [9] [ERROR] Error handling request /wheellog_csv/csv_to_gpx
2022-09-12T11:56:21.642725+00:00 app[web.1]: Traceback (most recent call last):
2022-09-12T11:56:21.642726+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.10/site-packages/gunicorn/workers/sync.py", line 136, in handle
2022-09-12T11:56:21.642728+00:00 app[web.1]:     self.handle_request(listener, req, client, addr)
2022-09-12T11:56:21.642728+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.10/site-packages/gunicorn/workers/sync.py", line 185, in handle_request
2022-09-12T11:56:21.642729+00:00 app[web.1]:     resp.write(item)
2022-09-12T11:56:21.642729+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.10/site-packages/gunicorn/http/wsgi.py", line 326, in write
2022-09-12T11:56:21.642730+00:00 app[web.1]:     self.send_headers()
2022-09-12T11:56:21.642730+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.10/site-packages/gunicorn/http/wsgi.py", line 322, in send_headers
2022-09-12T11:56:21.642731+00:00 app[web.1]:     util.write(self.sock, util.to_bytestring(header_str, "latin-1"))
2022-09-12T11:56:21.642731+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.10/site-packages/gunicorn/util.py", line 565, in to_bytestring
2022-09-12T11:56:21.642731+00:00 app[web.1]:     return value.encode(encoding)
2022-09-12T11:56:21.642732+00:00 app[web.1]: UnicodeEncodeError: 'latin-1' codec can't encode characters in position 161-166: ordinal not in range(256)
2022-09-12T11:56:21.642901+00:00 app[web.1]: [12/Sep/2022:11:56:21 +0000] "POST /wheellog_csv/csv_to_gpx HTTP/1.1" 500 0 "-" "-"
```

**Comment by b1oki** [comment]
issue with cyrillic filename

**Comment by b1oki** [comment]
Now work, download `unsupported_filename.gpx` if wrong charset
